# fly.toml app configuration file generated for shrink on 2023-10-01T22:51:10+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shrink"
primary_region = "sin"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]